import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Manejo Inteligente de Animais | especies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
